// Layer configuration for the pantropical thesis map.
// Each entry describes how to load the layer, how to colour it,
// and how to format its value in the click-to-query panel.

const THEMES = [
  { id: "overview", label: "Overview", description: "All thesis spatial layers together." },
  { id: "pnr", label: "Ch.2 — Natural Regeneration", description: "PNR cost–benefit categories and the carbon, biodiversity, cost and agricultural-overlap layers behind them. Awaiting: carbon/biodiversity/cost proxy rasters, agricultural overlap." },
  { id: "fragmentation", label: "Ch.3 — Fragmentation", description: "Current vs. post-regeneration fragmentation, and the effect of counting plantations as forest. Awaiting: natural-forest vs. tree-cover layer." },
  { id: "ghostroads", label: "Ch.4 — Ghost Roads", description: "Undocumented roads, their effect on fragmentation, and protected-area incursion. Awaiting: FFI-with-ghost-roads (processing), protected areas, satellite-vs-field-mapped comparison." }
];

// Classification for Δ-fragmentation layers: 4 discrete classes with a
// hatched pattern for "no change" (rather than a continuous diverging ramp).
const DELTA_FFI_CLASSES = {
  breaks: [
    { test: (v) => v < -0.1, color: "#1b5e20", label: "Strong decrease in fragmentation (ΔFFI < -0.1)" },
    { test: (v) => v >= -0.1 && v < 0, color: "#a5d6a7", label: "Decrease in fragmentation (-0.1 ≤ ΔFFI < 0)" },
    { test: (v) => v === 0, color: "#f0ead6", hatch: "#b8a97a", label: "No change (ΔFFI = 0)" },
    { test: (v) => v > 0, color: "#c9a66b", label: "Increase in fragmentation (ΔFFI > 0)" }
  ]
};

const LAYERS = [
  {
    id: "forest_loss",
    group: "Forest change",
    label: "Forest loss (2015–2025)",
    themes: ["overview", "fragmentation"],
    type: "xyz-filtered",
    filter: "loss",
    minLossYear: 15,
    tropicalClip: true,
    url: "https://tiles.globalforestwatch.org/umd_tree_cover_loss/v1.13/dynamic/{z}/{x}/{y}.png?tree_cover_density_threshold=30",
    attribution: "Hansen/UMD/Google/USGS/NASA, via Global Forest Watch",
    defaultOn: true,
    opacity: 0.85,
    legend: {
      type: "swatches",
      items: [{ color: "#e63946", label: "Forest loss, 2015–2025" }],
      note: "Live tiles from Global Forest Watch, recolored and clipped to the tropical belt client-side. Pixel query not available for this layer."
    },
    queryable: false
  },
  {
    id: "forest_gain",
    group: "Forest change",
    label: "Forest gain (5yr, height-based)",
    themes: ["overview", "fragmentation"],
    type: "xyz-filtered",
    filter: "gain",
    tropicalClip: true,
    url: "https://tiles.globalforestwatch.org/umd_tree_cover_gain_from_height/v20240126/default/{z}/{x}/{y}.png",
    attribution: "UMD/GLAD, via Global Forest Watch",
    defaultOn: false,
    opacity: 0.85,
    legend: {
      type: "swatches",
      items: [{ color: "#1f78d1", label: "Tree cover gain detected" }],
      note: "Live tiles from Global Forest Watch, clipped to the tropical belt client-side. Source encodes extra sub-classes (period/height) in RGB that aren't publicly documented, so this shows gain presence only, not sub-class. Pixel query not available for this layer."
    },
    queryable: false
  },
  {
    id: "forest_net_change",
    group: "Forest change",
    label: "Net change (loss vs. gain, pixel-level)",
    themes: ["overview", "fragmentation"],
    type: "xyz-netchange",
    lossUrl: "https://tiles.globalforestwatch.org/umd_tree_cover_loss/v1.13/dynamic/{z}/{x}/{y}.png?tree_cover_density_threshold=30",
    gainUrl: "https://tiles.globalforestwatch.org/umd_tree_cover_gain_from_height/v20240126/default/{z}/{x}/{y}.png",
    minLossYear: 15,
    attribution: "Hansen/UMD/Google/USGS/NASA + UMD/GLAD, via Global Forest Watch",
    defaultOn: false,
    opacity: 0.85,
    legend: {
      type: "swatches",
      items: [
        { color: "#e63946", label: "Net loss (2015–2025, no gain detected)" },
        { color: "#1f78d1", label: "Net gain (no loss detected)" },
        { color: "#8e44ad", label: "Both loss and gain detected (cleared then regrown)" }
      ],
      note: "Built by combining GFW's loss and gain tiles pixel-by-pixel client-side — GFW's own 'net change' layer is only available pre-aggregated to admin/district polygons. Clipped to the tropical belt. Pixel query not available for this layer."
    },
    queryable: false
  },
  {
    id: "current_ffi",
    group: "Forest fragmentation",
    label: "Current fragmentation (FFI)",
    themes: ["overview", "fragmentation"],
    alwaysQuery: true,
    type: "cog",
    url: "data/current_forest_ffi.tif",
    defaultOn: true,
    opacity: 0.8,
    resampleMethod: "bilinear",
    colorScale: { domain: [0, 1], palette: "FFI_ArcGIS" },
    unit: "index (0–1)",
    statKey: "currentFFI",
    statLabel: "Current fragmentation index"
  },
  {
    id: "regen_all_pnr_ffi",
    group: "Forest fragmentation",
    label: "Fragmentation after regeneration — all potential NR",
    themes: ["overview", "fragmentation", "pnr"],
    type: "cog",
    url: "data/regen_all_pnr_ffi.tif",
    defaultOn: false,
    opacity: 0.8,
    resampleMethod: "bilinear",
    colorScale: { domain: [0, 1], palette: "FFI_ArcGIS" },
    unit: "index (0–1)",
    statKey: "allPnrFFI",
    statLabel: "Fragmentation after all-PNR regeneration"
  },
  {
    id: "regen_hh_ffi",
    group: "Forest fragmentation",
    label: "Fragmentation after regeneration — holistic hotspot",
    themes: ["overview", "fragmentation", "pnr"],
    type: "cog",
    url: "data/regen_holistic_hotspot_ffi.tif",
    defaultOn: false,
    opacity: 0.8,
    resampleMethod: "bilinear",
    colorScale: { domain: [0, 1], palette: "FFI_ArcGIS" },
    unit: "index (0–1)",
    statKey: "hhFFI",
    statLabel: "Fragmentation after holistic-hotspot regeneration"
  },
  {
    id: "delta_all_pnr",
    group: "Forest fragmentation",
    label: "Δ Fragmentation — all potential NR (vs. current)",
    themes: ["overview", "fragmentation"],
    type: "cog-classified",
    url: "data/delta_ffi_all_pnr.tif",
    defaultOn: false,
    opacity: 0.85,
    classification: DELTA_FFI_CLASSES,
    unit: "Δ index (classified)",
    statKey: "deltaAllPnr",
    statLabel: "Δ Fragmentation, all-PNR scenario"
  },
  {
    id: "delta_hh",
    group: "Forest fragmentation",
    label: "Δ Fragmentation — holistic hotspot (vs. current)",
    themes: ["overview", "fragmentation"],
    type: "cog-classified",
    url: "data/delta_ffi_holistic_hotspot.tif",
    defaultOn: false,
    opacity: 0.85,
    classification: DELTA_FFI_CLASSES,
    unit: "Δ index (classified)",
    statKey: "deltaHH",
    statLabel: "Δ Fragmentation, holistic-hotspot scenario"
  },
  {
    id: "regen_category",
    group: "Natural regeneration opportunity",
    label: "Regeneration cost–benefit category",
    themes: ["overview", "pnr"],
    alwaysQuery: true,
    type: "cog",
    url: "data/regen_category_classes.tif",
    defaultOn: true,
    opacity: 0.75,
    resampleMethod: "nearest",
    categorical: true,
    discreteColors: [
      "#D3B7F1", "#BC92D9", "#BE71A4", "#A14BEF",
      "#BACDE1", "#5882B9", "#233D7F", "#000000",
      "#FAA9B9", "#FF72A0", "#F40550", "#AE0002"
    ],
    noData: 255,
    unit: "category",
    statKey: "regenCategory",
    statLabel: "Regeneration cost–benefit category",
    categoryLabels: {
      1: "Low cost, low carbon, low biodiversity",
      2: "Low cost, high carbon, low biodiversity",
      3: "Low cost, low carbon, high biodiversity",
      4: "Low cost, high carbon, high biodiversity  (= holistic hotspot)",
      5: "Medium cost, low carbon, low biodiversity",
      6: "Medium cost, high carbon, low biodiversity",
      7: "Medium cost, low carbon, high biodiversity",
      8: "Medium cost, high carbon, high biodiversity",
      9: "High cost, low carbon, low biodiversity",
      10: "High cost, high carbon, low biodiversity",
      11: "High cost, low carbon, high biodiversity",
      12: "High cost, high carbon, high biodiversity"
    }
  },
  {
    id: "pnr_score",
    group: "Natural regeneration opportunity",
    label: "PNR score (regeneration potential)",
    themes: ["overview", "pnr"],
    alwaysQuery: true,
    type: "cog",
    url: "data/pnr_score.tif",
    defaultOn: false,
    opacity: 0.75,
    resampleMethod: "bilinear",
    colorScale: { domain: [0, 1], palette: "Greens" },
    unit: "score (0–1)",
    statKey: "pnrScore",
    statLabel: "PNR score"
  },
  {
    id: "pnr_carbon",
    group: "Natural regeneration opportunity",
    label: "Carbon accumulation potential (from category dataframe)",
    themes: ["overview", "pnr"],
    alwaysQuery: true,
    type: "cog",
    url: "data/pnr_carbon.tif",
    defaultOn: false,
    opacity: 0.75,
    resampleMethod: "bilinear",
    colorScale: { domain: [0, 65], palette: "Greens" },
    unit: "carbon proxy (capped near 99th pctile)",
    statKey: "pnrCarbon",
    statLabel: "Carbon accumulation (dataframe)"
  },
  {
    id: "carbon_30yrs_main",
    group: "Natural regeneration opportunity",
    label: "Carbon accumulation, 30yr (main proxy, full res)",
    themes: ["overview", "pnr"],
    type: "cog",
    url: "data/carbon_30yrs_main.tif",
    defaultOn: false,
    opacity: 0.75,
    resampleMethod: "bilinear",
    colorScale: { domain: [0, 65], palette: "Greens" },
    unit: "carbon proxy",
    statKey: "carbon30yrMain",
    statLabel: "Carbon accumulation, 30yr (main)",
    note: "This may be the same source data as 'Carbon accumulation (dataframe)' above at higher native resolution — worth confirming which should be primary. Second carbon proxy not yet supplied."
  },
  {
    id: "bio_iucn_sup",
    group: "Natural regeneration opportunity",
    label: "Biodiversity — IUCN (supplementary proxy)",
    themes: ["overview", "pnr"],
    type: "cog",
    url: "data/bio_iucn_sup.tif",
    defaultOn: false,
    opacity: 0.75,
    resampleMethod: "bilinear",
    colorScale: { domain: [0, 106], palette: "Viridis" },
    noData: 255,
    unit: "IUCN-based score",
    statKey: "bioIucnSup",
    statLabel: "Biodiversity (IUCN proxy)"
  },
  {
    id: "extinction_risk_sup",
    group: "Natural regeneration opportunity",
    label: "Species extinction risk (supplementary proxy)",
    themes: ["overview", "pnr"],
    type: "cog",
    url: "data/extinction_risk_sup.tif",
    defaultOn: false,
    opacity: 0.75,
    resampleMethod: "bilinear",
    colorScale: { domain: [3, 106], palette: "Viridis" },
    noData: 255,
    unit: "wider extinction-risk score",
    statKey: "extinctionRiskSup",
    statLabel: "Species extinction risk (wider proxy)"
  },
  {
    id: "pnr_bio",
    group: "Natural regeneration opportunity",
    label: "Biodiversity benefit",
    themes: ["overview", "pnr"],
    alwaysQuery: true,
    type: "cog",
    url: "data/pnr_bio.tif",
    defaultOn: false,
    opacity: 0.75,
    resampleMethod: "bilinear",
    colorScale: { domain: [0, 0.15], palette: "Viridis" },
    unit: "biodiversity proxy (capped near 95th pctile; heavily right-skewed)",
    statKey: "pnrBio",
    statLabel: "Biodiversity benefit"
  },
  {
    id: "pnr_oppcosts",
    group: "Natural regeneration opportunity",
    label: "Land opportunity cost",
    themes: ["overview", "pnr"],
    type: "cog",
    url: "data/pnr_oppcosts.tif",
    defaultOn: false,
    opacity: 0.75,
    resampleMethod: "bilinear",
    colorScale: { domain: [0, 700], palette: "YlOrRd" },
    unit: "$ (capped near 90th pctile)",
    statKey: "pnrOppCost",
    statLabel: "Land opportunity cost"
  },
  {
    id: "pnr_implecosts",
    group: "Natural regeneration opportunity",
    label: "Implementation cost",
    themes: ["overview", "pnr"],
    type: "cog",
    url: "data/pnr_implecosts.tif",
    defaultOn: false,
    opacity: 0.75,
    resampleMethod: "bilinear",
    colorScale: { domain: [14, 291], palette: "YlOrRd" },
    unit: "$",
    statKey: "pnrImpleCost",
    statLabel: "Implementation cost"
  },
  {
    id: "pnr_nrcosts_total",
    group: "Natural regeneration opportunity",
    label: "Total regeneration cost",
    themes: ["overview", "pnr"],
    alwaysQuery: true,
    type: "cog",
    url: "data/pnr_nrcosts_total.tif",
    defaultOn: false,
    opacity: 0.75,
    resampleMethod: "bilinear",
    colorScale: { domain: [0, 900], palette: "YlOrRd" },
    unit: "$ (capped near 90th pctile)",
    statKey: "pnrTotalCost",
    statLabel: "Total regeneration cost"
  },
  {
    id: "ghost_roads",
    group: "Ghost roads",
    label: "Ghost roads — presence",
    themes: ["overview", "ghostroads"],
    alwaysQuery: true,
    type: "cog",
    url: "data/ghost_roads_presence.tif",
    defaultOn: true,
    opacity: 0.9,
    resampleMethod: "nearest",
    categorical: true,
    binary: true,
    trueColor: "#d7263d",
    noData: 255,
    unit: "presence",
    statKey: "ghostRoad",
    statLabel: "Ghost-road presence",
    categoryLabels: { 0: "No road detected", 1: "Road present" },
    regionNote: "Only covers the Sumatra–Borneo–Papua study region (Engert et al.-style ghost-roads analysis) — not the full tropical belt.",
    resolutionNote: "Source: 1 ha, shown here resampled to ~1 km for web display."
  },
  {
    id: "ghost_forest_mask",
    group: "Ghost roads",
    label: "Forest mask (ghost-road study area)",
    themes: ["overview", "ghostroads"],
    type: "cog",
    url: "data/ghost_forest_mask.tif",
    defaultOn: false,
    opacity: 0.6,
    resampleMethod: "nearest",
    categorical: true,
    binary: true,
    trueColor: "#0b6623",
    noData: 255,
    unit: "forest",
    statKey: "ghostForestMask",
    statLabel: "Forest (ghost-road study mask)",
    categoryLabels: { 0: "Not forest", 1: "Forest" },
    regionNote: "Only covers the Sumatra–Borneo–Papua study region."
  },
  {
    id: "natural_forest_binary",
    group: "Ghost roads",
    label: "Natural forest (Ch.4 study area)",
    themes: ["overview", "ghostroads"],
    type: "cog",
    url: "data/natural_forest_binary.tif",
    defaultOn: false,
    opacity: 0.6,
    resampleMethod: "nearest",
    categorical: true,
    binary: true,
    trueColor: "#1b7a3d",
    noData: 255,
    unit: "natural forest",
    statKey: "naturalForestBinary",
    statLabel: "Natural forest (Ch.4 study area)",
    categoryLabels: { 0: "Not natural forest", 1: "Natural forest" },
    regionNote: "Only covers the Sumatra–Borneo–Papua study region. Distinguishes natural forest from plantation, which plain tree-cover layers conflate."
  },
  {
    id: "ffi_pre_ghost_road",
    group: "Ghost roads",
    label: "FFI — before ghost roads (satellite only)",
    themes: ["overview", "ghostroads"],
    alwaysQuery: true,
    type: "cog",
    url: "data/ffi_pre_ghost_road.tif",
    defaultOn: false,
    opacity: 0.8,
    resampleMethod: "bilinear",
    colorScale: { domain: [0, 1], palette: "FFI_ArcGIS" },
    unit: "index (0–1)",
    statKey: "ffiPreGhostRoad",
    statLabel: "FFI before ghost roads",
    regionNote: "Only covers the Sumatra–Borneo–Papua study region."
  },
  {
    id: "ffi_post_ghost_road",
    group: "Ghost roads",
    label: "FFI — after ghost roads included",
    themes: ["overview", "ghostroads"],
    alwaysQuery: true,
    type: "cog",
    url: "data/ffi_post_ghost_road.tif",
    defaultOn: false,
    opacity: 0.8,
    resampleMethod: "bilinear",
    colorScale: { domain: [0, 1], palette: "FFI_ArcGIS" },
    unit: "index (0–1)",
    statKey: "ffiPostGhostRoad",
    statLabel: "FFI after ghost roads",
    regionNote: "Only covers the Sumatra–Borneo–Papua study region."
  },
  {
    id: "protected_areas",
    group: "Ghost roads",
    label: "Protected areas (IUCN Cat. II)",
    themes: ["overview", "ghostroads"],
    type: "geojson",
    url: "data/protected_areas.geojson",
    defaultOn: false,
    style: { color: "#0b6623", weight: 1.5, fillColor: "#0b6623", fillOpacity: 0.08 },
    legend: {
      type: "swatches",
      items: [{ color: "#0b6623", label: "Protected area boundary (IUCN Cat. II)" }],
      note: "WDPA polygons for the Ch.4 study area, used to show ghost-road incursion into protected land."
    }
  },
  {
    id: "tropical_tree_cover",
    group: "Reference layers",
    label: "Tropical tree cover (10m, WRI)",
    themes: ["overview", "fragmentation"],
    type: "xyz",
    url: "https://tiles.globalforestwatch.org/wri_tropical_tree_cover_extent/v20220922/tcd_40/{z}/{x}/{y}.png",
    attribution: "WRI Tropical Tree Cover, via Global Forest Watch",
    defaultOn: false,
    opacity: 0.75,
    legend: {
      type: "swatches",
      items: [{ color: "#8bc34a", label: "Tree cover, >40% canopy density" }],
      note: "Live tiles from Global Forest Watch — not reprocessed. Reference layer only, separate from the fragmentation analysis layers."
    },
    queryable: false
  },
  {
    id: "forest_landscape_integrity",
    group: "Reference layers",
    label: "Forest Landscape Integrity Index",
    themes: ["overview", "fragmentation"],
    type: "cog",
    url: "data/forest_landscape_integrity_tropics.tif",
    defaultOn: false,
    opacity: 0.75,
    resampleMethod: "bilinear",
    colorScale: { domain: [0, 10000], palette: "Greens" },
    noData: -9999,
    unit: "FLII score",
    statKey: "flii",
    statLabel: "Forest Landscape Integrity Index"
  }
];

const PALETTES = {
  YlOrRd: ["#ffffcc", "#ffeda0", "#fed976", "#feb24c", "#fd8d3c", "#fc4e2a", "#e31a1c", "#b10026"],
  RdBu: ["#67001f", "#b2182b", "#d6604d", "#f4a582", "#fddbc7", "#f7f7f7", "#d1e5f0", "#92c5de", "#4393c3", "#2166ac", "#053061"],
  Viridis: ["#440154", "#482878", "#3e4a89", "#31688e", "#26828e", "#1f9e89", "#35b779", "#6ece58", "#b5de2b", "#fde725"],
  Greens: ["#f7fcf5", "#e5f5e0", "#c7e9c0", "#a1d99b", "#74c476", "#41ab5d", "#238b45", "#006d2c", "#00441b"],
  FFI_ArcGIS: ["#267300", "#99E600", "#FFE600", "#E6BD73", "#A87000", "#FFFFFF"]
};

function getColorScale(cfg) {
  const colors = cfg.reverse ? [...PALETTES[cfg.palette]].reverse() : PALETTES[cfg.palette];
  return chroma.scale(colors).domain(cfg.domain);
}
